extends:
  # https://github.com/umijs/fabric/blob/master/src/eslint.ts
  - ./node_modules/@umijs/fabric/dist/eslint
  # https://github.com/import-js/eslint-plugin-import#typescript
  - plugin:import/recommended
  - plugin:import/typescript
  # https://prettier.io/docs/en/related-projects.html#eslint-integrations
  # `eslint-config-prettier`, turns off all ESLint rules that are unnecessary or might conflict with Prettier
  - prettier

rules:
  import/namespace: 2
  import/export: 2
